weights: yolov5s.pt
cfg: ./docker-repository/dataset/model-files/yolov5s_gate_test.yaml
data: ./docker-repository/dataset/model-files/test.yaml
hyp: data/hyp.scratch.yaml
epochs: 20
batch_size: 32
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: runs/train
entity: null
name: yolov5s_gate_test
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
world_size: 1
global_rank: -1
save_dir: runs/train/yolov5s_gate_test16
total_batch_size: 32
